version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb+srv://natnaelwondwoesn:rBBwT2s6s5YsEjsO@cluster0.0gsof12.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mongo_data: 