paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Register a new user and assign to free tier
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - full_name
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                  minimum: 8
                full_name:
                  type: string
                subscribeToNewsletter:
                  type: boolean
                  description: Whether the user wants to subscribe to the newsletter
                  default: false
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: User with this email already exists
      security: []

  /auth/token:
    post:
      tags:
        - Authentication
      summary: Login for access token
      description: Authenticate user and return access and refresh tokens
      operationId: loginForAccessToken
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: User email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  token_type:
                    type: string
                    example: "bearer"
        '401':
          description: Incorrect email or password
      security: []

  /auth/refresh-token:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      description: Get a new access token using refresh token
      operationId: refreshAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: New access token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                    example: "bearer"
        '401':
          description: Invalid or expired refresh token
      security: []

  /auth/me:
    get:
      tags:
        - Authentication
      summary: Get current user info
      description: Get information about the currently authenticated user
      operationId: getCurrentUserInfo
      responses:
        '200':
          description: User information retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated

  /auth/verify-email:
    post:
      tags:
        - Authentication
      summary: Verify email
      description: Verify user email with verification token. Users receive this token via email when they register.
      operationId: verifyEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email verified successfully"
        '400':
          description: Invalid verification token
      security: []

  /auth/request-password-reset:
    post:
      tags:
        - Authentication
      summary: Request password reset
      description: Request a password reset token. An email with a reset link will be sent to the specified email address if the account exists.
      operationId: requestPasswordReset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Password reset request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "If the email exists, a password reset link will be sent"
      security: []

  /auth/reset-password:
    post:
      tags:
        - Authentication
      summary: Reset password
      description: Reset user password with a valid token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - new_password
              properties:
                token:
                  type: string
                new_password:
                  type: string
                  format: password
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password reset successfully"
        '400':
          description: Invalid or expired reset token
      security: []

  /auth/update-newsletter-preference:
    post:
      tags:
        - Authentication
      summary: Update newsletter subscription preference
      description: Update the user's preference for receiving newsletters
      operationId: updateNewsletterPreference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - subscribeToNewsletter
              properties:
                subscribeToNewsletter:
                  type: boolean
                  description: Whether the user wants to subscribe to the newsletter
      responses:
        '200':
          description: Newsletter preference updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Failed to update newsletter preference
        '401':
          description: Unauthorized
      security:
        - bearerAuth: []

  /auth/request-login-code:
    post:
      tags:
        - Authentication
      summary: Request login code
      description: Request a one-time login code for passwordless authentication. A 6-digit code will be sent to the email address if it exists in the system.
      operationId: requestLoginCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Login code request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "If the email exists, a login code will be sent"
      security: []

  /auth/verify-login-code:
    post:
      tags:
        - Authentication
      summary: Verify login code
      description: Verify a one-time login code and return JWT tokens if valid
      operationId: verifyLoginCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  format: email
                code:
                  type: string
                  description: The 6-digit code sent to the user's email
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  token_type:
                    type: string
                    example: "bearer"
        '401':
          description: Invalid email or code, or the code has expired
      security: []

  /auth/resend-verification:
    post:
      tags:
        - Authentication
      summary: Resend verification email
      description: Resend the email verification link to a user who hasn't verified their email yet
      operationId: resendVerificationEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Verification email request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "If the email exists and is not verified, a verification link will be sent"
      security: []

components:
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        full_name:
          type: string
        service_tier:
          type: string
          enum: [FREE, BASIC, PRO, ENTERPRISE]
        is_active:
          type: boolean
        is_verified:
          type: boolean
        created_at:
          type: string
          format: date-time
        usage:
          type: object
          properties:
            requests_today:
              type: integer
            requests_reset_date:
              type: string
              format: date-time
            total_requests:
              type: integer
            storage_used_bytes:
              type: integer 